#! /bin/bash

set -e

# Change into top directory.
cd "$(dirname "$0")"
cd ..

python tests/whitelist.py
python2 -m vulture tests/whitelist.py
python2 -m vulture --exclude=external lab downward examples tests
