#! /bin/bash

# Test setup: see bitbucket-pipelines.yml

set -euo pipefail

BENCHMARKS="$DOWNWARD_BENCHMARKS"
REPO="$DOWNWARD_REPO"

if [[ $# -gt 1 ]]; then
    echo "usage: ./run-tests [--skip-experiments]"
    exit 2
fi

function cleanup {
    rm -rf examples/data
    rm -rf examples/ff/data
    rm -rf examples/pi/data
    rm -rf examples/planner/data
    rm -rf examples/simple/data
}

# Change into top directory.
cd "$(dirname "$0")"
cd ..

# Make lab available on the PYTHONPATH.
LAB=`realpath .`
echo "Checking lab at $LAB"
export PYTHONPATH=${LAB}
echo "PYTHONPATH: $PYTHONPATH"

cleanup

python2 -m py.test tests

# Run doctests.
cd lab
python -m doctest reports/__init__.py experiment.py tools.py
cd ..
cd downward
python -m doctest experiment.py
cd ..

# Check imports and unused/missing variables.
python -m pyflakes lab/calls lab/reports lab/*.py  # Don't check external dir.
python -m pyflakes downward examples tests setup.py docs/conf.py

./tests/find-dead-code

# Check code formatting.
pep8 --max-line-length=90 --exclude=*external*,data lab downward examples setup.py

# Check if documentation builds.
cd docs
make -B html
echo "Docs: file://$(pwd)/_build/html/index.html"
cd ..

echo "Code and style tests passed"

if [[ $# -gt 0 ]]; then
    exit
fi

cd examples

cd ff
./ff.py --all
cd ..

cd simple
./simple-exp.py --all
cd ..

cd pi
./pi.py --all
./pi-ext.py --help
cd ..

./report-external-results.py --all

# Only check downward code if $REPO exists.
if [ -d "$REPO" ]; then
    ./lmcut.py --all

    cd planner
    ./planner.py --all
    cd ..

    ./showcase-options.py --all

    cd ..
else
    echo
    echo "Repo $REPO is missing. Could not run downward tests."
fi

echo "Experiment tests passed"
