#! /bin/bash

# Test setup:
#
# $ sudo apt-get install pip
# $ sudo pip install -U pytest pep8 pyflakes sphinx

set -e

REPO='/home/jendrik/projects/Downward/downward'

# Change into top directory.
cd "$(dirname "$0")"
cd ..

# Make lab available on the PYTHONPATH.
LAB=`realpath .`
echo Checking lab at $LAB
if [ -z "$PYTHONPATH" ]; then
    # PYTHONPATH is empty.
    export PYTHONPATH=${LAB}
elif [[ "$PYTHONPATH" != *"$LAB"* ]]; then
    # LAB is NOT on the PYTHONPATH.
    export PYTHONPATH=${LAB}:${PYTHONPATH}
fi
echo PYTHONPATH: $PYTHONPATH

py.test-2.7 tests

# Run doctests.
cd lab
python -m doctest reports/__init__.py experiment.py tools.py
cd ..
cd downward
python -m doctest downward/suites.py
cd ..

EXAMPLES="lmcut.py showcase-options.py standard_exp.py \
    simple/simple-exp.py pi/pi.py pi/pi-ext.py planner/planner.py \
    planner/planner-ext.py"

# Check imports and unused/missing variables.
pyflakes lab/calls lab/reports lab/*.py  # Don't check external dir.
pyflakes downward
cd examples
pyflakes ${EXAMPLES}
cd ..

./tests/find-dead-code

# Check code formatting.
# Ignore under-indented continuation lines (E128) and allow longer lines.
PEP8_OPTS="--ignore=E128 --max-line-length=90"
pep8 $PEP8_OPTS --exclude=*external*,data lab
pep8 $PEP8_OPTS --exclude=suites.py downward
# Don't require two blank lines between each suite (E302).
pep8 $PEP8_OPTS --ignore=E302 downward/suites.py
cd examples
pep8 $PEP8_OPTS --max-line-length=120 --ignore=E302 ${EXAMPLES}
cd ..

# Check if documentation builds.
cd docs
make -B html
echo "Docs: file://$(pwd)/_build/html/index.html"
cd ..

# Run demo lab experiment.
cd examples/simple
rm -rf /tmp/simple-exp
./simple-exp.py --all
rm -rf /tmp/simple-exp
cd ../..

# Check pi experiment
cd examples/pi
rm -rf exp-pi*
./pi.py --all
./pi-ext.py --help
rm -rf exp-pi*
cd ../..

# Only check downward code if $REPO exists.
if [ -d "$REPO" ]; then
    cd examples
    rm -rf exp-*

    # Check example experiment.
    ./lmcut.py {1..8}

    # Check planner experiment.
    cd planner
    rm -rf exp-planner*
    ./planner.py --all
    ./planner-ext.py
    rm -rf exp-planner*
    cd ..

    # Run demo downward experiment.
    rm -rf data/showcase-options
    ./showcase-options.py --all

    rm -rf exp-*
    cd ..
else
    echo
    echo "Repo $REPO is missing. Could not run downward tests."
fi

echo TESTS PASSED
