#! /bin/bash
### Set name.
#$ -N %(name)s
### Set shell.
#$ -S /bin/bash
### Execute job from current working directory.
#$ -cwd
### Redirect stdout and stderr.
#$ -e %(errfile)s
#$ -o %(logfile)s
### Set queue.
#$ -q %(queue)s
### Number of tasks.
#$ -t 1-%(num_tasks)d
### Priority ([-1023,1024], default: 0).
#$ -p %(priority)d
### Restrict to certain machines.
%(host_spec)s
### Send mail when job finishes? -m can be e.g. (b)eginning, (e)nd, (n)ever.
%(notification)s

# TODO: Can we remove this?
export PATH=~/bin:$PATH
