#! /bin/bash
### Set name.
#$ -N %(name)s
### Set shell.
#$ -S /bin/bash
### Pass environment variables to the grid engine.
#$ -V
### Don't send emails.
#$ -m n
### Execute job from current working directory.
#$ -cwd
### redirect stdout and stderr
#$ -e %(errfile)s
#$ -o %(logfile)s
### Set queue (athlon_core.q => one core; athlon.q => whole CPU).
#$ -q %(queue)s
### Number of tasks
#$ -t 1-%(num_tasks)d
### Priority ([-1023,1024], default: 0)
#$ -p %(priority)d
