#! /bin/bash
### Set name.
#$ -N %(name)s
### Set shell.
#$ -S /bin/bash
### Execute job from current working directory.
#$ -cwd
### Redirect stdout and stderr.
#$ -e %(errfile)s
#$ -o %(logfile)s
### Set queue.
#$ -q %(queue)s
### Number of tasks.
#$ -t 1-%(num_tasks)d
### Priority ([-1023,1024], default: 0).
#$ -p %(priority)d
### Restrict to certain machines.
%(host_spec)s
### Send mail when job finishes? -m can be e.g. (b)eginning, (e)nd, (n)ever.
%(notification)s

declare -a RUN_IDS=(%(run_ids)s)
NUM_TASKS=%(num_tasks)d
if [ ${#RUN_IDS[@]} -ne $NUM_TASKS ]; then
    for ((i=0; i<$NUM_TASKS; i++)); do
        RUN_IDS[${i}]=${i}
    done
fi

if [ -z $PYTHONPATH ]; then
    export PYTHONPATH=$(pwd)
else
    export PYTHONPATH=$(pwd):$PYTHONPATH
fi

export PATH=~/bin:$PATH
